### ISSUE TITLE
UI as well as User Experience can be improved

### ISSUE THREAD

**Issue by dsaini17** [vibsdrockstar/AttendanceApp#1]
UI such as :- 
https://github.com/dsaini17/AttendanceTracker
can be used
and for adding subjects , Database such as :- 
https://github.com/dsaini17/TaskManager
can be used .
This will increase the reach and make the application more user oriented

**Comment by vibsdrockstar** [comment]
dis was a simple attendance app.However the pocket attendance app which is an upgraded version of dis wud have some extra features as suggested by you. That app I wud complete by 5th september

**Comment by dsaini17** [comment]
I can help with Database

**Comment by vibsdrockstar** [comment]
ya i wud b glad if u help me with database
